#!/bin/sh -efu

# Copyright 2011-2012 Intel Corporation
# Author: Artem Bityutskiy
# License: GPLv2

srcdir="$(readlink -ev -- ${0%/*}/..)"
PATH="$srcdir:$srcdir/email:$srcdir/external/libshell:$PATH"

. shell-error
. shell-args
. shell-signal
. aiaiai-sh-functions
. aiaiai-email-sh-functions

PROG="${0##*/}"
export message_time="yes"

# This is a small trick to make sure the script is portable - check if 'dash'
# is present, and if yes - use it.
if can_switch_to_dash; then
	exec dash -euf -- "$srcdir/$PROG" "$@"
	exit $?
fi

show_usage()
{
	cat <<-EOF
Usage: $PROG [options] <cfgfile.ini>

The mbox file containing the patches to test is expected to come from stdin
(unless --input option is specified).

<cfgfile.ini>          - the configuration file.

Options:
  -i, --input=MBOX       use the MBOX file instead of stdin;
  -C, --confdir=CDIR     path to the directory containing the defconfig files
                         (those you specify in the config file); by default the
                         defconfig files are assumed to be part of the
                         <kernel-tree>; this option makes it possible to use
                         stand-alone defconfig files instead;
  -p, --preserve         preserve all the temporary files - do not clean up;
      --test-mode        test mode - work as usually, but do not actually
                         send replies;
      --bisectability    test bisectability;
      --sparse           check with sparse while building;
      --smatch           check with smatch while building;
      --cppcheck         check with cppcheck;
      --coccinelle       check with coccinelle;
  -v, --verbose          be verbose;
  -h, --help             show this text and exit.
EOF
}

fail_usage()
{
	[ -z "$1" ] || printf "%s\n" "$1"
	show_usage
	exit 1
}

preserve=
verbose=
mbox=
tmpdir=
cleanup_handler()
{
	rm $verbose -rf -- "$mbox" >&2

	if [ -n "$preserve" ]; then
		verbose "Preserved tmpdir: $tmpdir"
	else
		[ -z "$tmpdir" ] || verbose "Removing $tmpdir";
		rm -rf -- "$tmpdir" >&2
	fi
}
set_cleanup_handler cleanup_handler

# List currently supported projects.
list_projects()
{
	local prj

	LC_ALL=C sed -n -e "s/^\[prj_\(.*\)\]$/\1/p" "$cfgfile" | \
	    while read -r prj; do
		# Get project description
		local descr
		ini_config_get_or_die descr "$cfgfile" "prj_$prj" "description"

		local email="$cfg_ownmail_local+$prj@$cfg_ownmail_domain"
		printf "* %s\n" "$prj ($email): $descr"
	done
}

# Send an e-mail reply to the patch author. This function relies on the various
# global variables, most notably:
#   o "from" - address of the submitter of the patch under test, our reply will
#              be sent there
#   o "to" - addresses of the recipients of the patch under test, these will be
#            carbon-copied
#   o "subj" - subject of patch under test, the reply will have the same
#              subject
#   o "id" - message ID of the patch under test, the reply will have reference
#            this ID
send_email()
{
	compose_email "$from" "$to" "$subj" "$id" > "$tmpdir/mail"

	[ -z "$verbose" ] || cat -- "$tmpdir/mail" >&2

	if [ -z "$test_mode" ]; then
		mutt -x -H "$tmpdir/mail" </dev/null
	else
		verbose "Do not actually send the email - we are in test mode"
	fi
}

# This function is called when the target project for the patch under test was
# not specified. It sends a sensible reply back to the submitter, without
# carbon-copying anyone else.
error_no_project_specified()
{
	to=
	send_email <<EOF
Sorry, but you have not specified the project name. Please, specify it
using the "+" symbol in the e-mail address of $cfg_ownname. For example,
"$cfg_ownmail_local+XYZ@$cfg_ownmail_domain" would mean project "XYZ".

List of projects $cfg_ownname supports:

$(list_projects)

Please, contact "$cfg_adminname" <$cfg_adminmail>
if you have any questions.
EOF
	exit 0
}

# This function is called when submitters specify a non-existing project. It
# sends a sensible reply back to the submitter, without carbon-copying anyone
# else.
error_project_not_found()
{
	to=
	send_email <<EOF
Sorry, but project "$prj" is not supported. List of projects $cfg_ownname
currently supports:

$(list_projects)

Please, contact "$cfg_adminname" <$cfg_adminmail>
if you have any questions.
EOF
	exit 0
}

# This function is called when the 'aiaiai-test-patchest' fails. This most
# probably means a bug or configuration issues. This function sends an e-mail
# notification about this. The notification is sent to the patch submitter and,
# depending on the "reply_to_all" configuration option, everyone in "To:" and
# "Cc:".
error_test_patchset_failed()
{
	send_email <<EOF
Sorry, but an internal $cfg_ownname error happened. Please, contact
"$cfg_adminname" <$cfg_adminmail>.
EOF
	exit 0
}

# This is a helper function which sends a notification about the patch under
# test being accepted for testing. The notification e-mail is sent to the patch
# submitter and, depending on the "reply_to_all" configuration option, everyone
# in "To:" and "Cc:".
send_accepted_email()
{
	send_email <<EOF
Your patch or patch-set:

$(fetch_header_per_patch "Subject" < "$mbox" | sort)

has been accepted by $cfg_ownname and scheduled for testing.
EOF
}

# This is a helper function which sends the results of testing back to the
# patch submitter and, depending on the "reply_to_all" configuration option,
# everyone in "To:" and "Cc:".
send_results_email()
{
	send_email <<EOF
$cfg_built_preamble

$(fetch_header_per_patch "Subject" < "$mbox" | sort)

Project: $cfg_name ($cfg_descr)

Configurations: $cfg_configs

$(cat -- $tmpdir/test-patchset.log)
EOF
}

TEMP=`getopt -n $PROG -o i:,C:,p,v,h --long test-mode,input:,confdir:,preserve,bisectability,sparse,smatch,cppcheck,coccinelle,verbose,help -- "$@"` ||
	fail_usage ""
eval set -- "$TEMP"

mbox=
confdir=
test_mode=
bisectability=
sparse=
smatch=
cppcheck=
coccinelle=

while true; do
	case "$1" in
	-i|--input)
		mbox="$(opt_check_read "$1" "$2")"
		shift
		;;
	-C|--confdir)
		confdir="$(opt_check_dir "$1" "$2")"
		shift
		;;
	-p|--preserve)
		preserve="--preserve"
		;;
	--test-mode)
		test_mode=y
		;;
	--bisectability)
		bisectability="--bisectability"
		;;
	--sparse)
		sparse="--sparse"
		;;
	--smatch)
		smatch="--smatch"
		;;
	--cppcheck)
		cppcheck="--cppcheck"
		;;
	--coccinelle)
		coccinelle="--coccinelle"
		;;
	-v|--verbose) verbose=-v
		;;
	-h|--help)
		show_usage
		exit 0
		;;
	--) shift; break
                ;;
	*) fail_usage "Unrecognized option: $1"
		;;
	esac
	shift
done

[ "$#" -eq 1 ] || die "Insufficient or too many arguments"

program_required "mutt" ""
program_required "grep" ""
program_required "sed" ""
program_required "formail" ""

cfgfile="$1"; shift

# Save the mbox to a temporary file if it comes from stdin
if [ -z "$mbox" ]; then
	mbox="$(mktemp -t "$PROG.mbox.XXXX")"
	cat > "$mbox"
fi

fetch_header_or_die subj "Subject" < "$mbox"
fetch_header_or_die from "From" < "$mbox"
fetch_header_or_die id "Message-Id" < "$mbox"
msgname="$from: $subj (Message-Id: $id)"

echo >&2
verbose "Testing mbox: \"$msgname\""
verbose "parsing config file \"$cfgfile\""

parse_config "$cfgfile"

mkdir $verbose -p -- "$cfg_workdir" >&2

tmpdir="$(mktemp --tmpdir="$cfg_workdir" -dt "$PROG.XXXX")"
mv $verbose -- "$mbox" "$tmpdir/mbox" >&2
mbox="$tmpdir/mbox"

to="$(fetch_header "To" < "$mbox")"
cc="$(fetch_header "Cc" < "$mbox")"

# Either "To:" or "Cc:" must exist
if [ -z "$to" ] && [ -z "$cc" ]; then
       die "Neither \"To:\" nor \"Cc:\" header found"
fi

# Find out the project name
prj="$(fetch_project_name "$to" "$cfg_ownmail")"

verbose "Project \"$prj\""

# Reject the e-mail if the project has not been specified
if [ -z "$prj" ]; then
	error_no_project_specified
fi

# Fetch project configuration
parse_prj_config "$cfgfile" "$prj"

# Check if we have this project in our config file
if [ -z "$cfg_name" ]; then
	error_project_not_found
fi

# Merge the "To" and "Cc" addresses
to="$(merge_addresses "$to" "$cc")"

if [ "$cfg_reply_to_all" != "1" ]; then
	to=
else
	# Strip own address
	to=$(strip_address "$to" "$cfg_ownmail")
fi

# Notify the sender that the patches have been accepted
if [ "$cfg_accept_notify" = "1" ]; then
	verbose "Sending \"accepted\" e-mail"
	send_accepted_email
fi

# Test the path (or patch-set)
verbose "Test configs \"$cfg_configs\" branch \"$cfg_branch\" of \"$cfg_path\""
aiaiai-test-patchset $verbose $preserve $bisectability $sparse $smatch $cppcheck $coccinelle \
	-i "$mbox" -j "$cfg_jobs" -c "$cfg_branch" -w "$tmpdir" \
	${confdir:+-C "$confdir"} \
	${cfg_unwanted_keywords:+-K "$cfg_unwanted_keywords"} -- \
	${cfg_kmake_opts:+-M "$cfg_kmake_opts"} \
	"$cfg_path" "$cfg_configs" > "$tmpdir/test-patchset.log" ||
{
	verbose "aiaiai-test-patchset failed"
	error_test_patchset_failed
}

# Mail the results of testing
verbose "Test is finished, sending back the results"
send_results_email
